### ISSUE TITLE
mdns: cannot ping host name anymore after several minutes

### ISSUE THREAD

**Issue by jonasvanpelt** [tass-belgium/picotcp#309]
Issue found on ESP8266
- Chips starts up and initializes mdns
- I can ping the chosen hostname
- After several minutes I can only ping the IP address, not the hostname anymore.

**Comment by jelledevleeschouwer** [comment]
Hi @jonasvanpelt,

I took a look at it and ran mDNS for almost an hour on my VM but I was unable to reproduce the error. After an hour I was still able to ping the hostname. If I find some this week (maybe tomorrow), I'll try to reproduce on the hitex-platform (LPC4357) in a real environment. 

In the meanwhile, if you would find some time, could you please check some things for me? 
* **In Wireshark, do you see the ping-requesting host sending an mDNS-request to resolve the hostname on the network?**
* **Through Semihosting or UART, when mDNS-debugging enabled, do you see something like below?**
```
_________________________________________________________________________________
READ EVENT!
Received data from 10.10.1.1:5353
>>>>>>> QDcount: 1, ANcount: 0, NScount: 0, ARcount: 0
>>>>>>> RCVD a plain mDNS query:
Question RCVD for 'host.local'
Finding query cookie..
```
* **And right below that, do you see:**
```
Multicast response sent succesfully!
```
* **In Wireshark again, do you see an mDNS-answer from the ESP8266 with an A record with the hostname?**

I understand if you don't have any time at all, then I'll try on the hitex-platform.

Thanks in advance,

Best regards,
Jelle

**Comment by jonasvanpelt** [comment]
@jelledevleeschouwer  Thanks for looking into it so fast.
![screenshot from 2015-10-06 16 32 37](https://cloud.githubusercontent.com/assets/5087468/10311668/090b8868-6c48-11e5-86ca-da5e57c893e3.png)

I attached the wireshark output of the pinging that fails.

The other stuff you mention I will try later!

**Comment by jelledevleeschouwer** [comment]
You're welcome, Hmm, first odd thing I notice, is that somebody else (192.168.1.254) tries to answer the query, who is that? And, does the response of 192.168.1.254 contain an A record with the queried hostname? Or some other records with that hostname?

Since I have nothing to do tonight anyway, I'll be having fun with the hitex-board :smile:

**Comment by jonasvanpelt** [comment]
@jelledevleeschouwer. That is my ubuntu server. I'm going to check with the mdns debugging now and check some more stuff in Wireshark.

**Comment by jonasvanpelt** [comment]
@jelledevleeschouwer 
I checked the things you asked for:
- After a while when I cannot ping the hostname anymore, no mdns debugging is printed anymore. In the beginning, when it is still working, I see indeed the successful read events ...
- In Wireshark I see only a query response from my Ubuntu server, but he is multicasting another A record ....
Looks like no mdns activity anymore on my chip :-(.

**Comment by jelledevleeschouwer** [comment]
@jonasvanpelt 

Thanks a lot for checking. I've finally managed to get my demo of mDNS working again after quite some trouble to get my SysTick working again. Only with my old dev-repo though, if I use latest development,  pico_ms_tick-counter seems to be random and my interrupt seems to happen around 1 second instead of 1 millisecond, which totally broke it, but I think this is another issue I need to look into another time.

So if I understand correct, the host sends its mDNS-requests correct, the ESP receives them for a while and answers correct but eventually he will not even receive the mDNS-requests anymore? If that's the case, I assume that the issue is on another layer, otherwise you would still see the "READ EVENT!"-logs.

And secondly I understand the Ubuntu Server hasn't anything to do with it since he doesn't reply with A-records with the record-name 'barlights.local.', right? Otherwise he is acting as a proxy, and there's a chance that isn't taken into account in my implementation. But normally he shouldn't proxy records out of the blue if I recall correct.

Sorry for this last request again, but can you maybe attach a .pcap-file to this thread of the network-traffic so I can examine a bit more in-depth? I don't have an Ubuntu Server so maybe that could be useful in the debugging. And maybe the last console-output as well? Sorry about all these requests, but I have another platform and another application, so I can't really reproduce the issue properly.

I'm running the mDNS-demo overnight to check if this isn't a endurance-issue and if can still ping the hostname in the morning. 

Hope we're getting there!

Thanks,
Jelle

**Comment by jonasvanpelt** [comment]
Don't apology for your requests! it's cool how much time you put in this! Thanks a lot for that!

- The ESP does not receive the mDNS-requests anymore indeed. I also have the feeling something else is going on since I don't get the read events. But it's not that pico is dead because I can still ping and use the webserver etc.

- I don't know whether it has something to do with it but when I look at my log, during the time mDNS is still up, I get a lot of read events for other host names. But of course pico cannot find a match for these requests ..

- My server does not reply with the record-name 'barlights.local'. It is just multicasting another record (from a website that I run on my server)

- Please forget the Wireshark output I attached before, it was wrong. On the picture you see that the ESP answers with a A-record, ... so that was a situation where it still worked. If I check Wireshark when it is broken, there is no answer of course ...

- I added you on Skype so I can send you a .pcap file tonight. (Cannot attach files like that on Github apparently)

Jonas.

**Comment by jelledevleeschouwer** [comment]
Thanks, added you as well. I don't think the stream of mDNS-queries in the beginning has anything to do with it, I have them as well and it doesn't trigger a failure of some sort. I still find it a kind of strange that the server seems to reply with another record on the query with a totally different name, though. But I'll keep the server out of the issue nonetheless. I'll have to figure out why the mDNS_module doesn't receive the queries anymore.

Jelle

**Comment by phalox** [comment]
Hey guys!

What's the status on this issue? Is it fixed, can it then be closed? Is there a more specific issue that could be described in a new item?

**Comment by jelledevleeschouwer** [comment]
@phalox 

For what I know, I don't think the problem is solved. I was unable to reproduce the error myself, so couldn't really fix it. I think @jonasvanpelt has a more recent update on this. 
@jonasvanpelt, where you able to figure out why the mDNS didn't seem to receive queries, or did it?

**Comment by jonasvanpelt** [comment]
@phalox , @jelledevleeschouwer . Problem still occurs on my setup. I tried using static IP in stead of DHCP but that did not fix the problem. I should dive into it again!
