### ISSUE TITLE
C89 compatibility issues (zero-sized arrays)

### ISSUE THREAD

**Issue by mateuszviste** [tass-belgium/picotcp#325]
Hello,

This is something I already discussed with Maxime Vincent a month or so ago - picoTCP has some troubles with C89 compatibility (meaning - it is not C89 compatible), and I think this is bad for portability.

The problem is that there are places that use zero-sized arrays, like:
struct blah {
  int foo;
  char bar[0];
};

Maxime fixed this in many places in 1.6.2, but in current trunk there are still at least two such places - see the attached patch (which is not really a patch, because it provides no solution, it only points to the problem).

![iso-9899-1990-6 5 4 2](https://cloud.githubusercontent.com/assets/9503501/11240426/ec186b1e-8df2-11e5-804c-646aa3f00a5e.png)
[zero-sized-arrays.patch.txt](https://github.com/tass-belgium/picotcp/files/37786/zero-sized-arrays.patch.txt)

**Comment by danielinux** [comment]
please make a pull request ISO sending text patches.

**Comment by danielinux** [comment]
Fixed in d142986 .

**Comment by mateuszviste** [comment]
I'm sorry to get back to this, but I noticed the same problem still applies to some other files in the development branch, as seen below. Please tell if I should rather report this in a separate (new) issue.

```
wcc -DGENERIC -DPICO_SUPPORT_DHCPC -DPICO_SUPPORT_DNS_CLIENT -DPICO_SUPPORT_ETH -DPICO_SUPPORT_ICMP4 -DPICO_SUPPORT_ICMP6 -DPICO_SUPPORT_IGMP -DPICO_SUPPORT_IPV4 -DPICO_SUPPORT_IPV4FRAG -DPICO_SUPPORT_IPV6 -DPICO_SUPPORT_IPV6FRAG -DPICO_SUPPORT_MCAST -DPICO_SUPPORT_MLD -DPICO_SUPPORT_PING -DPICO_SUPPORT_SNTP_CLIENT -DPICO_SUPPORT_TCP -DPICO_SUPPORT_TFTP -DPICO_SUPPORT_UDP -Iinclude -Imodules -wx -bt=dos -ml -DPICO_COMPILE_TIME=2015 -DARCHDOS modules/pico_mld.c
Open Watcom C16 Optimizing Compiler Version 1.9
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
modules/pico_mld.c(49): Error! E1020: Dimension cannot be 0 or negative
modules/pico_mld.c(57): Error! E1020: Dimension cannot be 0 or negative
modules/pico_mld.c(69): Error! E1020: Dimension cannot be 0 or negative
modules/pico_mld.c: 1179 lines, included 8559, 0 warnings, 3 errors
Error(E42): Last command making (all) returned a bad status
Error(E02): Make execution terminated
```

**Comment by mateuszviste** [comment]
I might be writing to myself here, I guess no notification is sent when an update is made on a closed issue :) I will fork this into a separate case.
