### ISSUE TITLE
[IGMP] When receiving an IGMPv2 query pico does not send a membership report in backwards compatibility mode.

### ISSUE THREAD

**Issue by ISY-Thomas** [tass-belgium/picotcp#343]
When pico is subscribed to a multicast stream and an IGMPv2 general query is sent to it, there is no response. PicoTCP is backwards compatible with IGMPv2 so it should send a valid reply back.
A membership response indicating to which multicast stream the DUT is subscribed is expected.

reproduce:
sudo ./run.sh --test igmpsendgeneralquery testcases/hardware/igmp_bench_dut.txt

**Comment by ISY-Thomas** [comment]
I have been looking more into what/why this is an issue, and I have seen that the IGMPv2 compatibility is working but only in a specific scenario. Let me explain:

When compatibility is to be tested, the following scenario is played out:

- PicoTCP subscribes to an Mcast stream
       -> PicoTCP sends IGMPv3 Membership Report

- IGMPv2 Membership query is sent to PicoTCP

- PicoTCP is expected to send back IGMPv2 Membership Report for subscribed mcast group

This above sequence is not working. It does however work when the following scenario is checked:

- PicoTCP subscribes to an mcast stream
       -> PicoTCP sends IGMPv3 Membership Report
       -> PicoTCP sends IGMPv3 Membership Report

- IGMPv2 Membership query is sent to PicoTCP

- PicoTCP is expected to send back IGMPv2 Membership Report for subscribed mcast group

**Please note that when PicoTCP is allowed to send two IGMPv3 membership reports, PicoTCP will then respond to an IGMPv2 Membership query.** PicoTCP is sending those two Membership reports because of the state change from "non-member" to "delaying member", and the next one for the state change from "delaying member" to "idle member". If we send a IGMPv2 MQ right after receiving the first IGMPv3 MR (no-member to delaying member), no response is given by PicoTCP

When testing the above scenario, with no compatibility mode required, so the following scenario, and then it works as expected:

- PicoTCP subscribes to an mcast stream
       -> PicoTCP sends IGMPv3 Membership Report

- IGMPv3 Membership query is sent to PicoTCP

- PicoTCP sends back IGMPv3 Membership Report for subscribed mcast group

Could you investigate if this really is the correct behaviour? This seems inconsistent.

**Comment by roel0** [comment]
Thanks for the closer look Thomas, the first case should indeed work. I'll check it out

**Comment by roel0** [comment]
While picoTCP is in the Delaying Member state, a compatibility switch can take place which will cause the final state machine to be in a deadlock.

This is caused by 
"  Whenever a host changes its compatibility mode, it cancels all its
   pending response and retransmission timers." - rfc3376 $7.2.1

The rfc didn't made it clear to me (yet) what to do in this situation. I'm amusing since the timer is canceled, we need to automatically go to idle state without any other action. After that, thanks to the received query, we immediately go back to Delaying Member and start a new timer in IGMPv2 mode. 

I will dig deeper for a solution the coming days

**Comment by ISY-Thomas** [comment]
Some more information, the following does not regard compatibility issues, but is only for IGMPv3.
So for IGMPv3 when a General Query is sent to PicoTCP the following works:

    PicoTCP subscribes to an mcast stream
    -> PicoTCP sends IGMPv3 Membership Report
    IGMPv3 Membership query is sent to PicoTCP
    PicoTCP sends back IGMPv3 Membership Report for subscribed mcast group

When a Group-Specific or Group-And-Source-Specific query is sent to PicoTCP, and the following is **not** done, PicoTCP has weird behaviour:

PicoTCP subscribes to an mcast stream
-> PicoTCP sends IGMPv3 Membership Report
-> PicoTCP sends IGMPv3 Membership Report
    IGMPv3 Group/Group-and-source specific Membership query is sent to PicoTCP
    PicoTCP sends back IGMPv3 Membership Report for subscribed mcast group

What I see in Wireshark is that PicoTCP instead of replying with an IGMPv3 Membership report, it responds with a Group-Specific query directed to 224.0.0.22, which is the IP address that Version 3 **Reports** are to be sent to. This seems however to be linked to wrong behaviour in the complete IGMP module when not waiting before receiving two IGMPv3 Membership Reports, before sending Queries to PicoTCP.

**Comment by roel0** [comment]
The Issue should be fixed in 6ad04feeb5475c3d42144fcdc6fe036cea3d17a6 
However I have currently no test setup, I will verify as soon as possible.

**Comment by ISY-Thomas** [comment]
Will try to perform some checks on this already with my testing setup over here. Will let you know what happens.

**Comment by ISY-Thomas** [comment]
Hi Roel,

Did some checking and the issue is still present unfortunately.. Both the IGMPv2 issue, and the IGMPv3 Group/Group-and-source specific Membership query are still present..

**Comment by roel0** [comment]
That's weird, I will setup the testframework in order to debug it.
